---
title: Capstone Project Proposal
author: Donald Ruud
date: '2021-06-16'
slug: capstone-project-proposal
categories: []
tags: []
---

# Under Construction...


# Overview

My project is centered on Data Science articles. These articles contain information on what is currently happening in our industry and how we talk about it. We primarily use theory to determine what trends are up and coming in our industry. I believe we can approach this from a more systematic perspective. We should perform a text analysis on Data Science articles published over the past 20 years so that we can visualize the most prominent topics and better understand how our industry has developed. Through this visualization we may be able to draw critical insights about where our industry is headed.

# Context

Data Science is a relatively new industry that has only recently begun to solidify. We can trace elements of Data Science far back into history, but only within the past few decades has computing technology advanced enough to make widespread statistical analyses feasible. Data Science as a field has shifted a lot over the past 20 years. Specifically, the way we talk about Data Science and the various concepts that are important.

What is the problem?
Currently, we base our thoughts on the "next big thing" in Data Science on theory. Theory in of itself is not a bad place to start, but it's not always right when it comes to predicting changes in the industry. We need to make sure that we are prepared as industry professionals to use and understand new technology as it emerges. Being behind the curve in Data Science can seriously hamper your capabilities.

# Proposal

How has the way we talk about Data Science changed over time?
Where is the conversation heading?

I intend to scrape text data from the abstracts of a newsletter related to Data Science over a period of approximately 20 year. Then I can apply Latent Dirichlet Allocation (LDA) to aid in the analysis of each article's abstract. I intend to generate a language consistency score which can then be visualized over time to show how industry language has shifted.

Before I dive into any modeling, I'll need to explore and thoroughly clean my dataset. Since I'm scraping the data from the internet I will need to do an extensive amount of text processing before it is in a useable format. Once I have everything clean, it should be fairly simple to analyze it and generate the relevant graphs.

The ultimate goal of this project is to generate an interactive dashboard using R-Shiny which allows the user to explore the most prevalent words throughout the sampled time period. Additionally, I hope to provide some general insights about how industry terminology has evolved over time on the default display of the app.

# Conclusion



Pre-mature cell culture death costs this Bio-technology company time, labor, and materials. A significant number of the culture deaths can be attributed to unexpected, elevated lactate levels within the culture. By building a model which can effectively predict lactate levels, we can identify other variables which have an outsized effect on lactate. These variables can be used to identify failures within the process so that effective countermeasures can be deployed.

The generalizability of this project is somewhat limited but not entirely absent. This project is specific to this lab as it does focus on their data. While the results of the analysis cannot be effectively transferred to another company, the analysis process can. Another company could use the same framework to analyze their own data and determine drivers of lactate within their own systems.

This project is limited to essentially problem identification. The model will tell us what drives lactate, but it won't tell us how to address those drivers. The next step is to look closely at the main drivers and determine how they can be changed to help reduce further instances of elevated lactate levels. That particular step falls more under the domain of process improvement. Once specific countermeasures have been created, it would be possible to devise an experiment and see if the countermeasures actually succeed in reducing instances of elevated lactate levels.